### PR TITLE
Adds ability to use docker to run site

### PR DESCRIPTION
**Pull request by haroon-sheikh**
Towards #1 
- Adds `docker-compose.yml` to bootup docker container
- Updates `.gitignore` to ignore vendor directory, etc.
- Updates `_config.yml` to exclude vendor

### CODE REVIEW

**Comment by scottmathson** [comment]
Thanks @haroon-sheikh going to test this locally first. Appreciate the addition!

**Comment by scottmathson** [comment]
In an effort to add any pre-requisites and make running as simple as possible, I think we should link to Docker Docs in `README.md` for installing: https://docs.docker.com/engine/installation/

**Comment by haroon-sheikh** [comment]
Done. Added the link into README.md

**Comment by scottmathson** [comment]
Thanks again @haroon-sheikh will merge this shortly. Cheers and Happy Hacktoberfest!

**Comment by scottmathson** [comment]
Removed Travis CI as well, no previous .yml file for it - disregard any build failures.

**Pull request merged**
